I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/location_sets.rpy", line 9, in script
    $ game.main()
ScriptError: could not find label 'player_bedroom'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\main.py", line 635, in main
    run(restart)
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/location_sets.rpy", line 9, in script
    $ game.main()
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'player_bedroom'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
YoutubeVNGame 1.0
Wed Jul 10 17:48:34 2024
